#ifndef TYPES_H
#define TYPES_H

enum item_type {
    TYPE_WEAPON,
    TYPE_ARMOR,
    TYPE_RECOVERY,
    TYPE_QUEST,
};

enum item {
    ITEM_SWORD_COPPER,
    ITEM_CHEST_LEATHER,
    ITEM_POTION,
    ITEM_KEY,
};

enum armor_slot {
    SLOT_HEAD,
    SLOT_CHEST,
    SLOT_LEG,
    SLOT_GLOVE,
    SLOT_BOOT,
};
enum {
    LEN_NAME_CHARACTER = 16,
    LEN_NAME_ITEM = 32,
    SIZE_ITEM = 255,
    SIZE_PARTY = 4,
};

enum job {
    JOB_FIGHTER,
    JOB_THIEF,
    JOB_MAGE,
    JOB_ROGUE,
    JOB_PALADIN,
    JOB_ASSASSIN,
    JOB_COUNT
};
enum status {
    STATUS_OKAY,
    STATUS_NOT_FOUND,
    STATUS_INVALID_INPUT,
    STATUS_NULL_INPUT,
    STATUS_LONG_INPUT,
    STATUS_LIST_FULL,
    STATUS_EMPTY,
    STATUS_INVALID_OPTION
};

enum selection { SELECTION_VALID, SELECTION_QUIT, SELECTION_INVALID };

enum menu_option {
    MENU_ADD,
    MENU_VIEW,
    MENU_CHANGE,
    MENU_REMOVE,
    MENU_SORT,
    MENU_COUNT
};

enum sort {
    SORT_NAME,
    SORT_STRENGTH,
    SORT_AGILITY,
    SORT_INTELLIGENCE,
    SORT_STAMINA,
    SORT_RESILIENCE,
    SORT_SPIRIT,
    SORT_COUNT
};

enum order { ORDER_ASCENDING, ORDER_DESCENDING, ORDER_COUNT };

#endif
